### ISSUE TITLE
esp module with commands and notifications

### ISSUE THREAD

**Issue by srgantmoomoo** [srgantmoomoo/postman#49]
esp module acts weird with commands & notifications. when trying to toggle it with the toggle command it will enable but disabling will crash. notifications appear for it when enabling but the disabling notifications do not appear.

**Comment by TwoThreeTwo** [comment]
Another thing, when you click esc on hud editor, it gives a null pointer exception not sure if it's an issue on my end lol

**Comment by srgantmoomoo** [comment]
> Another thing, when you click esc on hud editor, it gives a null pointer exception not sure if it's an issue on my end lol

Does it crash the game? If so can u give crash log.

**Comment by TwoThreeTwo** [comment]
Yeah, it does crash the game (that's why I said it gives a null Pointer Exception), I'll do it again and then clear any info that has my irl name and such and send the log 😉

**Comment by srgantmoomoo** [comment]
Why would it have ur name

**Comment by TwoThreeTwo** [comment]
bc when I got my computer and signed in with microsoft it had my irl name, i can't rly change it (I think) so I always gotta clear some info before I post it, and I was busy cuzz of scool but I'll send the log.

**Comment by TwoThreeTwo** [comment]
java.lang.NullPointerException: null
	at me.srgantmoomoo.postman.impl.clickgui.front.HudEditor.onDisable(HudEditor.java:42) ~[HudEditor.class:?]
	at me.srgantmoomoo.postman.framework.module.Module.disable(Module.java:117) ~[Module.class:?]
	at me.srgantmoomoo.postman.impl.clickgui.front.HudEditor.onUpdate(HudEditor.java:31) ~[HudEditor.class:?]
	at me.srgantmoomoo.postman.framework.module.ModuleManager$$Lambda$230/736727906.accept(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51]
	at me.srgantmoomoo.postman.framework.module.ModuleManager.onUpdate(ModuleManager.java:148) ~[ModuleManager.class:?]
	at me.srgantmoomoo.postman.backend.event.EventProcessor.onTick(EventProcessor.java:51) ~[EventProcessor.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_EventProcessor_onTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[23:33:12] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

**Comment by TwoThreeTwo** [comment]
based moomoo <3
